name: Generate Snake

on:
  schedule: # Atualiza a cada 24 horas
    - cron: "0 0 * * *"
  workflow_dispatch: # Permite rodar manualmente
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: GeorgePeixoto
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push snake.svg to the output branch
        uses: crazy-max/github-action-push-assets@v1
        with:
          branch: output
          base_branch: main
          directory: dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
